name: vipe
channels:
  - nvidia/label/cuda-12.8.0
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - cuda-nvcc
  - eigen
  - zlib
  - libcusparse-dev
  - libcublas-dev
  - libcusolver-dev